server:
  servlet:
    context-path: /dinner_clients_api/api/v1/

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USER_NAME_DATA_BASE}
    password: ${PASSWORD_DATA_BASE}
    url: jdbc:mysql://localhost:3306/evalart_reto
    initialization-mode: always
    initialize: true

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none